### ISSUE TITLE
Upgrade mongoose on this project

### ISSUE THREAD

**Issue by michaelbarnard** [A24Group/candidate-status-transformet#8]
Spawned from https://github.com/A24Group/apiG/issues/1731

This ticket is to upgrade mongoose on this project. We need to do this in order to support the new mongo version (We aim to run on 4.4).

### Basic steps to upgrade:
```
npm install mongoose@5.10.6
```
Ensure lodash is at least at version `4.17.10`, if not do an npm install for it.
Update the Dockerfile.mongo to look as below
```dockerfile
FROM mongo:4.4.1

RUN touch /var/log/mongodb.log && chmod 766 /var/log/mongodb.log

CMD ["mongod", "--logpath", "/var/log/mongodb.log", "--logappend", "--nojournal"]
```
You also need to create a `Dockerfile.mongo_legacy` file with the following content
```dockerfile
FROM mongo:4.0.20

RUN touch /var/log/mongodb.log && chmod 766 /var/log/mongodb.log

CMD ["mongod", "--logpath", "/var/log/mongodb.log", "--logappend", "--nojournal"]
```
In the `cloudbuild.yaml`, after the initial test has build, rebuild the database container with the new file
```yaml
# Build mongo legacy
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ '-c', 'docker build -t database --no-cache --file Dockerfile.mongo_legacy .' ]
```
Then copy paste the compose up section and add with '--force-recreate' and '--renew-anon-volumes' after. args should resemble below.
```yaml
  args: ['up', '--force-recreate', '--renew-anon-volumes', '--exit-code-from', 'candidate-status-transformet']
```
Go through the project and fix all methods listed here https://mongoosejs.com/docs/deprecations.html (Take note whether or not you have to change mongration scripts)

Remove options from the mongo config. Take note of any non default options as these will have to be added to the connection string via url query params. (This is done in Ansible)

Run the tests and ensure they pass (might require a few updates due to the deprecation changes).

### Ansible
 - Update ansible vaults so that the mongo connection urls have the same non-default properties as the options used to have.

**Comment by kkroese** [comment]
@michaelbarnard just check but I don't think we ever used this. we can probably not do this work and maybve even archive this project.

**Comment by michaelbarnard** [comment]
These tickets were created for any project that had mongoose in it's package.json. It does seem that this project was never fully implemented. Closing ticket
